#!/system/bin/sh
# adb: wrapper to run adb from terminal
# osm0sis @ xda-developers

dir="$(cd "$(dirname "$0")"; pwd)";

export HOME=$dir;
export TMPDIR=$dir;
export LD_LIBRARY_PATH=$dir
arch=`getprop ro.product.cpu.abi`
if [ $arch = "armeabi-v7a" ];then
    $dir/adb.bin-armeabi "$@";
else
    $dir/adb_binary "$@";
fi