#!/system/bin/sh
# adb: wrapper to run adb from terminal
# osm0sis @ xda-developers

dir="$(cd "$(dirname "$0")"; pwd)";

export HOME=$dir;
export TMPDIR=$dir;
export LD_LIBRARY_PATH=$dir
$dir/adb.bin "$@";

