name: ADBKIT CI
on:
  workflow_dispatch:
    inputs:
      clone_code_runner:
        description: 'Clone Code Runner'
        required: false
        default: 'ubuntu-latest'
      windows_runner:
        description: 'Windows Runner'
        required: false
        default: 'windows-latest'
      mac_runner:
        description: 'Mac Runner'
        required: false
        default: 'macos-latest'
      linux_runner:
        description: 'Linux Runner'
        required: false
        default: 'ubuntu-latest'
  repository_dispatch:
    types:
      - api

jobs:
  clone-code:
    name: Clone Code in ${{ github.event.inputs.clone_code_runner}}
    runs-on: ${{ github.event.inputs.clone_code_runner}}
    steps:
      - name: Checkout current code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      # github.workspace folder is adb_kit root folder
      - name: Checkout adb_kit_extension code
        uses: actions/checkout@v4
        with:
          repository: 'mengyanshou/adb_kit_extension'
          token: ${{ secrets.GH_PAT }}
          ref: 'main'
          path: "${{ github.workspace }}/packages/adb_kit_extension"

      - name: Checkout termux_api_plugin code
        uses: actions/checkout@v4
        with:
          repository: 'nightmare-space/termux_api_plugin'
          token: ${{ secrets.GH_PAT }}
          ref: 'main'
          path: "${{ github.workspace }}/packages/termux_api_plugin"

      - name: Checkout user_center_frontend code
        uses: actions/checkout@v4
        with:
          repository: 'mengyanshou/user_center_frontend'
          token: ${{ secrets.GH_PAT }}
          ref: 'main'
          path: "${{ github.workspace }}/packages/user_center_frontend"

      - name: Checkout behavior_api code
        uses: actions/checkout@v4
        with:
          repository: 'mengyanshou/behavior_api'
          token: ${{ secrets.GH_PAT }}
          ref: 'main'
          path: "${{ github.workspace }}/packages/behavior_api"

      - name: Checkout ni CLI code
        uses: actions/checkout@v4
        with:
          repository: 'mengyanshou/ni'
          token: ${{ secrets.GH_PAT }}
          ref: 'main'
          path: "${{ github.workspace }}/ni"
      - name: Checkout File Manager
      # https://github.com/nightmare-space/file_manager_private
        uses: actions/checkout@v4
        with:
          repository: 'nightmare-space/file_manager_private'
          token: ${{ secrets.GH_PAT }}
          ref: 'main'
          path: "${{ github.workspace }}/packages/file_manager"
      - name: Checkout Android Tool
      # https://github.com/nightmare-space/android_tool
        uses: actions/checkout@v4
        with:
          repository: 'nightmare-space/android_tool'
          token: ${{ secrets.GH_PAT }}
          ref: 'main'
          path: "${{ github.workspace }}/packages/android_tool"
      # https://github.com/nightmare-space/dart_adb
      - name: Checkout Dart ADB
        uses: actions/checkout@v4
        with:
          repository: 'nightmare-space/dart_adb'
          token: ${{ secrets.GH_PAT }}
          ref: 'main'
          path: "${{ github.workspace }}/packages/dart_adb"
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}
          key: code-${{ hashFiles('**/pubspec.lock') }}
          # enableCrossOsArchive
          enableCrossOsArchive : true
          restore-keys: |
            code-

  build-linux:
    name: Build Linux DEB
    runs-on: ${{ github.event.inputs.linux_runner }}
    environment: default
    needs: clone-code
    steps:
      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}
          key: code-
          enableCrossOsArchive : true

      - name: Move file
        run: |
          mv "${{ github.workspace }}/scripts/github_actions/pubspec_overrides.yaml" "${{ github.workspace }}/"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup other environment
        if: github.event.inputs.linux_runner != 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          # tray manager need
          sudo apt-get install libayatana-appindicator3-dev

      - name: Setup CLI environment
        run: |
          cd ${{ github.workspace }}/ni
          dart pub get

      - name: Building...
        run: |
          export PATH=$PATH:${{ github.workspace }}/ni
          nic release --build-linux-deb
          
      - name: Upload..
        run: |
          export PATH=$PATH:${{ github.workspace }}/ni
          nic default -u



  build-mac:
    name: Build Mac DMG
    runs-on: ${{ github.event.inputs.mac_runner }}
    needs: clone-code
    environment: default
    steps:
      - name: Run on ${{ github.job.runs-on }} 
        run: echo "This job runs on ${{ github.job.runs-on }}"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}
          key: code-
          enableCrossOsArchive : true

      - name: Move file
        run: |
          mv "${{ github.workspace }}/scripts/github_actions/pubspec_overrides.yaml" "${{ github.workspace }}/"
    
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/..

      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup CLI environment
        run: |
          cd ${{ github.workspace }}/ni
          dart pub get
          
      - name: Setup other environment
        run: |
          # brew install create-dmg
          npm install -g appdmg
        
      - name: Building&&Packaging
        run: |
          export PATH=$PATH:${{ github.workspace }}/ni
          nic release --build-mac-dmg
          # ./scripts/dmg/create_dmg.sh

      - name: Upload To Private Server
        run: |
          export PATH=$PATH:${{ github.workspace }}/ni
          nic default -u
            
  build-windows:
    name: Build Windows Portable
    runs-on: ${{ github.event.inputs.windows_runner }}
    environment: default
    needs: clone-code
    steps:
      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}
          key: code-
          enableCrossOsArchive : true

      - name: Move file
        run: |
          Move-Item -Path "${{ github.workspace }}/scripts/github_actions/pubspec_overrides.yaml" -Destination "${{ github.workspace }}/"
    
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Setup CLI environment
        if: always()
        run: |
          cd ${{ github.workspace }}\ni
          dart pub get

      - name: Building...
        if: always()
        shell: cmd
        run: |
          set PATH=%PATH%;${{ github.workspace }}\ni
          nic release --build-win-zip

      - name: Upload
        if: always()
        shell: cmd
        run: |
          set PATH=%PATH%;${{ github.workspace }}\ni
          nic default -u